name: Node.js CI

on: [push]

jobs:
  build-sample-web:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build and test for sample_web
      run: |
        cd sample_web
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
