name: playwright

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-sample-web:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies for playwright
        uses: microsoft/playwright-github-action@v1
      - name: npm install, build for sample_web
        working-directory: ./sample_web
        run: |
          npm install
          npm run build --if-present
          npm run start&
      - name: npm install, build and test for sample_web with playwright
        working-directory: ./playwright
        run: |
          npm install
          npm run build --if-present
          npm run test
        env:
          CI: true
